name: Haskell CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Update indices
      run: cabal update
    - name: Install dependencies
      run: cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: cabal test
